In [1]:
import pandas as pd
import numpy as np
import random
from faker import Faker
from datetime import datetime, timedelta

fake = Faker("en_IN")

In [3]:
# Cities where patients come from

cities = [
    "Bhubaneswar",
    "Cuttack",
    "Puri",
    "Sambalpur",
    "Rourkela",
    "Berhampur",
    "Balasore",
    "Delhi",
    "Mumbai",
    "Bangalore",
    "Hyderabad",
    "Chennai",
    "Kolkata"
]


# List of diseases

diseases = [
    "Diabetes",
    "Hypertension",
    "Heart Disease",
    "Asthma",
    "Cancer",
    "COVID-19",
    "Pneumonia",
    "Kidney Stone",
    "Migraine",
    "Fracture",
    "Dengue",
    "Typhoid"
]


# Hospital departments

departments = [
    "Cardiology",
    "Neurology",
    "Orthopedics",
    "General Medicine",
    "Oncology",
    "Pediatrics",
    "Gynecology",
    "Pulmonology",
    "Nephrology"
]


# Doctors list

doctors = [
    "Dr. Amit Kumar",
    "Dr. Priya Sharma",
    "Dr. Rajesh Das",
    "Dr. Neha Singh",
    "Dr. Vivek Mishra",
    "Dr. Anjali Sahu",
    "Dr. Arjun Rao",
    "Dr. Sneha Patel",
    "Dr. Mohan Roy",
    "Dr. Pooja Verma"
]


# Blood groups

blood_groups = [
    "A+",
    "A-",
    "B+",
    "B-",
    "AB+",
    "AB-",
    "O+",
    "O-"
]


# Payment methods

payment_modes = [
    "Cash",
    "UPI",
    "Credit Card",
    "Debit Card",
    "Insurance"
]


# Insurance companies

insurance_companies = [
    "Star Health",
    "Niva Bupa",
    "ICICI Lombard",
    "HDFC ERGO",
    "Care Health",
    "None"
]


print("All master lists created successfully!")

All master lists created successfully!

In [4]:
print(cities)

['Bhubaneswar', 'Cuttack', 'Puri', 'Sambalpur', 'Rourkela', 'Berhampur', 'Balasore', 'Delhi', 'Mumbai', 'Bangalore', 'Hyderabad', 'Chennai', 'Kolkata']

In [5]:
columns = [
    "Patient_ID",
    "Patient_Name",
    "Gender",
    "Age",
    "Blood_Group",
    "City",
    "Disease",
    "Department",
    "Doctor",
    "Admission_Date",
    "Discharge_Date",
    "Hospital_Stay",
    "Surgery",
    "Surgery_Type",
    "Medicine_Cost",
    "Lab_Charge",
    "Room_Charge",
    "Doctor_Fee",
    "Total_Bill",
    "Amount_Paid",
    "Pending_Amount",
    "Payment_Mode",
    "Feedback_Rating",
    "Insurance",
    "Insurance_Provider"
]

In [22]:
records = []


num_records = 10000


for i in range(num_records):


    patient_id = f"P{i+1:05d}"


    name = fake.name()


    gender = random.choice(
        ["Male","Female"]
    )


    age = random.randint(
        1,90
    )


    blood = random.choice(
        blood_groups
    )


    city = random.choice(
        cities
    )


    # Disease selection

    disease = random.choice(
        list(disease_department.keys())
    )


    # Automatic department

    department = disease_department[disease]


    # Automatic doctor

    doctor = random.choice(
        doctor_mapping[department]
    )


    # Dates

    admission = (
        datetime(2025,1,1)
        +
        timedelta(
            days=random.randint(0,364)
        )
    )


    stay=random.randint(1,10)


    discharge = (
        admission
        +
        timedelta(days=stay)
    )


    # Surgery

    surgery_type = surgery_mapping[disease]


    if surgery_type=="None":
        surgery="No"
    else:
        surgery="Yes"



    # Bill calculation

    total_bill=random.randint(
        cost_mapping[disease][0],
        cost_mapping[disease][1]
    )


    medicine=int(total_bill*0.30)

    room=int(total_bill*0.35)

    doctor_fee=int(total_bill*0.20)


    lab=(
        total_bill
        -
        medicine
        -
        room
        -
        doctor_fee
    )


    amount_paid=random.randint(
        int(total_bill*0.60),
        total_bill
    )


    pending_amount=(
        total_bill
        -
        amount_paid
    )


    feedback=random.randint(
        1,5
    )


    insurance=random.choice(
        ["Yes","No"]
    )


    if insurance=="Yes":

        provider=random.choice(
            insurance_companies[:-1]
        )

    else:

        provider="None"



    records.append([

        patient_id,
        name,
        gender,
        age,
        blood,
        city,
        disease,
        department,
        doctor,
        admission.date(),
        discharge.date(),
        stay,
        surgery,
        surgery_type,
        medicine,
        lab,
        room,
        doctor_fee,
        total_bill,
        amount_paid,
        pending_amount,
        random.choice(payment_modes),
        feedback,
        insurance,
        provider

    ])


print("10000 records generated")

10000 records generated

In [7]:
df = pd.DataFrame(records, columns=columns)

In [8]:
df.shape

(10000, 25)

In [9]:
df.head()

,Patient_ID,Patient_Name,Gender,Age,Blood_Group,City,Disease,Department,Doctor,Admission_Date,...,Lab_Charge,Room_Charge,Doctor_Fee,Total_Bill,Amount_Paid,Pending_Amount,Payment_Mode,Feedback_Rating,Insurance,Insurance_Provider
0,P00001,Panini Karpe,Female,34,O-,Sambalpur,Typhoid,Nephrology,Dr. Rajesh Das,2025-02-21,...,3707,19521,6331,43606,31675,11931,Cash,4,Yes,HDFC ERGO
1,P00002,Charita Bhardwaj,Female,32,A+,Bhubaneswar,Dengue,General Medicine,Dr. Arjun Rao,2025-04-04,...,4465,7763,6734,21434,18101,3333,Debit Card,4,No,None
2,P00003,Kai Sachdev,Female,66,B-,Bhubaneswar,Pneumonia,Cardiology,Dr. Amit Kumar,2025-08-14,...,4243,17419,1141,28989,23522,5467,Debit Card,3,No,None
3,P00004,Viraj Deo,Male,61,B-,Mumbai,Hypertension,Nephrology,Dr. Sneha Patel,2025-04-01,...,4741,12317,4089,25540,15459,10081,Debit Card,5,Yes,Niva Bupa
4,P00005,Amara Ramesh,Male,87,O+,Rourkela,Dengue,General Medicine,Dr. Sneha Patel,2025-01-31,...,4634,10269,5465,29329,19899,9430,Cash,4,Yes,HDFC ERGO

In [10]:
disease_department = {

    "Heart Disease": "Cardiology",

    "Hypertension": "Cardiology",

    "Diabetes": "General Medicine",

    "Asthma": "Pulmonology",

    "COVID-19": "Pulmonology",

    "Pneumonia": "Pulmonology",

    "Cancer": "Oncology",

    "Kidney Stone": "Nephrology",

    "Migraine": "Neurology",

    "Fracture": "Orthopedics",

    "Dengue": "General Medicine",

    "Typhoid": "General Medicine"
}


print("Disease Department Mapping Created")

Disease Department Mapping Created

In [11]:
print(disease_department["Kidney Stone"])

Nephrology

In [12]:
doctor_mapping = {

    "Cardiology": [
        "Dr. Amit Kumar",
        "Dr. Priya Sharma"
    ],


    "General Medicine": [
        "Dr. Pooja Verma"
    ],


    "Pulmonology": [
        "Dr. Anjali Sahu"
    ],


    "Oncology": [
        "Dr. Mohan Roy"
    ],


    "Nephrology": [
        "Dr. Arjun Rao"
    ],


    "Neurology": [
        "Dr. Sneha Patel"
    ],


    "Orthopedics": [
        "Dr. Rajesh Das",
        "Dr. Vivek Mishra"
    ]
}


print("Doctor Mapping Created")

Doctor Mapping Created

In [13]:
surgery_mapping = {

    "Heart Disease": "Heart Surgery",

    "Kidney Stone": "Kidney Surgery",

    "Fracture": "Bone Surgery",

    "Cancer": "Tumor Removal",


    "Hypertension": "None",

    "Diabetes": "None",

    "Asthma": "None",

    "COVID-19": "None",

    "Pneumonia": "None",

    "Migraine": "None",

    "Dengue": "None",

    "Typhoid": "None"
}


print("Surgery Mapping Created")

Surgery Mapping Created

In [14]:
print(surgery_mapping["Heart Disease"])

Heart Surgery

In [15]:
cost_mapping = {

    "Heart Disease": (60000,120000),

    "Cancer": (80000,200000),

    "Kidney Stone": (40000,90000),

    "Fracture": (30000,80000),

    "Diabetes": (5000,20000),

    "Hypertension": (5000,15000),

    "Asthma": (5000,25000),

    "COVID-19": (10000,50000),

    "Pneumonia": (15000,45000),

    "Migraine": (3000,10000),

    "Dengue": (10000,25000),

    "Typhoid": (10000,20000)
}


print("Cost Mapping Created")

Cost Mapping Created

In [16]:
print(cost_mapping["Cancer"])

(80000, 200000)

In [17]:
disease = "Heart Disease"

department = disease_department[disease]

doctor = random.choice(doctor_mapping[department])

surgery = surgery_mapping[disease]

cost_range = cost_mapping[disease]


print("Disease:", disease)
print("Department:", department)
print("Doctor:", doctor)
print("Surgery:", surgery)
print("Cost Range:", cost_range)

Disease: Heart Disease
Department: Cardiology
Doctor: Dr. Amit Kumar
Surgery: Heart Surgery
Cost Range: (60000, 120000)

In [23]:
df.to_csv(
"../dataset/Hospital_Management_Records.csv",
index=False
)


df.to_excel(
"../dataset/Hospital_Management_Records.xlsx",
index=False
)


print("Dataset saved successfully")

Dataset saved successfully

In [24]:
df.shape

(10000, 25)

In [25]:
df[['Disease','Department','Doctor']].head(10)

         Disease        Department           Doctor
0        Typhoid        Nephrology   Dr. Rajesh Das
1         Dengue  General Medicine    Dr. Arjun Rao
2      Pneumonia        Cardiology   Dr. Amit Kumar
3   Hypertension        Nephrology  Dr. Sneha Patel
4         Dengue  General Medicine  Dr. Sneha Patel
5         Cancer         Neurology   Dr. Neha Singh
6         Dengue        Nephrology   Dr. Rajesh Das
7       Diabetes       Pulmonology    Dr. Mohan Roy
8  Heart Disease       Orthopedics  Dr. Anjali Sahu
9  Heart Disease        Cardiology  Dr. Pooja Verma